### ISSUE TITLE
Region column of DataFrame from preprocessing.get_process() only got upacked for data from capacity factors.

### ISSUE THREAD

**Issue by JohannesBehrens** [sedos-project/data_adapter#14]
The region column only got unpacked correctly for data from the capacity factors file. For data from other files the corresponding DataFrames hold packed and unevaluated region data. (see screenshot below)

This problem could perhaps be solved by adding something like the following to line 61 of preprocessing.py:
else:
        df['region'] = df['region'].apply(eval)

![grafik](https://user-images.githubusercontent.com/120372257/226849000-0a080958-2d6a-4858-89d7-9e42a576988a.png)

**Comment by henhuy** [comment]
This is due to erroneous metadata where type of region column is "text" instead of "text array".
We have to fix this in metadata from OEP.
If you want to see it working, you could manually fix region field type in metadata of each process.
Example (region field in `modex_tech_wind_turbine_onshore.json`):
```
{
    "description": "Region in Germany",
    "isAbout": [],
    "name": "region",
    "type": "text array",
    "valueReference": []
},
```
Afterwards, regions should "explode" as expected....
